# SPDX-FileCopyrightText: © 2021 Jeff C. Jensen
# SPDX-License-Identifier: MIT
#
# Modifications Copyright © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
#
# This file contains portions from Jeff C. Jensen under MIT and
# modifications and modifications by Xronos Inc. under BSD-3-Clause.
---
- name: apt update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr
    force_apt_get: true # aptitude may not be installed
  become: true

- name: Stat /var/cache/xronos_ubuntu_common_ansible_upgraded
  ansible.builtin.stat:
    path: /var/cache/xronos_ubuntu_common_ansible_upgraded
  register: upgraded

- name: Set fact apply_upgrades
  ansible.builtin.set_fact:
    apply_upgrades: "{{ (ubuntu_apt_upgrade == 'always')
      or ((ubuntu_apt_upgrade == 'once') and not upgraded.stat.exists) }}"

- name: apt update
  ansible.builtin.import_tasks: apt-update.yml

- name: python update
  ansible.builtin.import_tasks: python.yml

- name: Install Ansible prerequisites
  ansible.builtin.import_tasks: ansible.yml

- name: Configure message of the day (motd)
  ansible.builtin.include_tasks: login-motd.yml
  when: ubuntu_trim_motd

- name: Disable unattended upgrades
  ansible.builtin.include_tasks: unattended-upgrades.yml
  when: ubuntu_disable_unattended_upgrades
    and ansible_distribution == 'Ubuntu'

- name: Configure timezone and ntp
  ansible.builtin.import_tasks: time.yml

- name: Write /var/cache/xronos_ubuntu_common_ansible_upgraded
  when: apply_upgrades
  ansible.builtin.copy:
    content: ""
    dest: /var/cache/xronos_ubuntu_common_ansible_upgraded
    force: false
  become: true

- name: Query restart required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: stat_result
  changed_when: stat_result.stat.exists
  notify: Restart server
