# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: apt install python3-pip
  ansible.builtin.apt:
    pkg:
      - python3-pip
    state: "{{ ubuntu_apt_upgrade | ternary('latest', 'present') }}"
  become: true

- name: pip install python3 tools
  ansible.builtin.apt:
    pkg:
      - python3-virtualenv
      - python3-setuptools
      - python3-psutil 
    state: "{{ ubuntu_apt_upgrade | ternary('latest', 'present') }}"
  become: true
