---
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Query restart required
  register: _stat_result
  ansible.builtin.stat:
    path: /var/run/reboot-required

- name: Reboot
  when: _stat_result.stat.exists
  become: true
  ansible.builtin.reboot:
