# SPDX-FileCopyrightText: (c) 2021 Jeff C. Jensen
# SPDX-License-Identifier: MIT
#
# Modifications Copyright (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
#
# This file contains portions from Jeff C. Jensen under MIT 
# and modifications by Xronos Inc. under BSD-3-Clause.
---
- name: apt install tzdata
  become: true
  ansible.builtin.apt:
    pkg:
      - tzdata
 
- name: Set timezone
  when: ubuntu_timezone | length > 0
  become: true
  community.general.timezone:
    name: "{{ ubuntu_timezone }}"

- name: Install ntp
  when: ubuntu_ntp_enable
  become: true
  ansible.builtin.apt:
    pkg: ntp

- name: Enable ntp
  when: ubuntu_ntp_enable
  become: true
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: true
