# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Stat /etc/apt/apt.conf.d/20auto-upgrades
  ansible.builtin.stat:
    path: /etc/apt/apt.conf.d/20auto-upgrades
  register: stat

- name: Disable apt periodic update of package lists
  when: stat.stat.exists
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^APT::Periodic::Update-Package-Lists "\\d";$'
    line: 'APT::Periodic::Update-Package-Lists "0";'
  become: true

- name: Disable apt periodic download of upgradable packages
  when: stat.stat.exists
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^APT::Periodic::Download-Upgradeable-Packages "\\d";$'
    line: 'APT::Periodic::Download-Upgradeable-Packages "0";'
  become: true

- name: Disable apt periodic autoclean
  when: stat.stat.exists
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^APT::Periodic::AutocleanInterval "\\d";$'
    line: 'APT::Periodic::AutocleanInterval "0";'
  become: true

- name: Disable apt auto upgrade
  when: stat.stat.exists
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^APT::Periodic::Unattended-Upgrade "\\d";$'
    line: 'APT::Periodic::Unattended-Upgrade "0";'
  become: true

- name: Systemd disable service apt-daily-upgrade
  ansible.builtin.systemd:
    service: apt-daily-upgrade
    enabled: false
    masked: true
  become: true

- name: Apt uninstall automatic updates
  ansible.builtin.apt:
    pkg:
      - ubuntu-release-upgrader-gtk
      - ubuntu-release-upgrader-core
      - update-manager
      - update-manager-core
      - update-notifier
      - update-notifier-common
    state: absent
  become: true

- name: Stat apt ESM hook
  ansible.builtin.stat:
    path: /etc/apt/apt.conf.d/20apt-esm-hook.conf
  register: stat

- name: Apt backup ESM hook
  when: stat.stat.exists
  ansible.builtin.copy:
    remote_src: true
    src: /etc/apt/apt.conf.d/20apt-esm-hook.conf
    dest: /etc/apt/apt.conf.d/20apt-esm-hook.conf.bak
    force: false
  become: true

- name: Apt disable ESM hook
  when: stat.stat.exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/apt/apt.conf.d/20apt-esm-hook.conf
    force: true
  become: true

- name: Ubuntu pro query apt_news setting
  ansible.builtin.command:
    cmd: pro config show apt_news
  changed_when: false
  failed_when: false
  become: true
  register: apt_news

- name: Ubuntu pro disable apt_news
  ansible.builtin.command:
    cmd: pro config set apt_news=false
  become: true
  when: "'apt_news True' in apt_news.stdout"
